// import coverOne from "./public/"

export const featuredProjects = [
  {
    id: "02",
    title: "Aquatrack",
    description:
      "AquaTrack is the innovative platform connecting fish farmers to a worldwide market, providing data-driven insights, and promoting sustainable practices.",
    coverImg: "/aquatrack-landing.jpg",
    gradient: "from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://www.aquatrackinc.com/management-system",
    role: "Lead Frontend Developer",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "TailwindCSS",
      "Shadcn",
      "PWA",
    ],
    features: [
      "Setup the frontend architecture, using NextJS, ReduxThunk. every endpoint are managed independently to improve performance and scalebility for the data fetching",
      "Lead 3 Frontend developer and 2 Interns during this product building",
      "Implemented a Secure Login with HTTPOnly Cookie",
      "Implemented Charts using Rechart",
      "Implemented Adding task and a real time reminder",
      "Delivered 2weeks ealiar before the deadline",
      "Enlighthen the client on features they need to add that's not in their PRD",
      "Implemented a subscription model, users can subscribe to premiunm plan using PayStack for making payment.",
      "Worked on Complex forms and making every bit responsive on all screens",
      "Worked closely with the backend team and design team to always be in sync with the product goal",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },
  {
    id: "01",
    title: "EASEPLAN",
    description:
      "An event planning platform that connects event owners to event planners and vendors could be viable in countries in Africa.",
    coverImg: "/EasePlan.jpg",
    gradient: "from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]",
    githubLink: "",
    siteLink: "https://www.easeplan.io",
    role: "Co-founder / Frontend Lead",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "MUI",
      "TailwindCSS",
      "PWA",
    ],
    features: [
      "Waitlist system, that endedup validation 698 users",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between vendors and customers",
      "Users can find vendors base on their current location",
      "Wallet system, vendors can recieve money from customer",
      "Auto matching system between vendors and users",
      "KYC integration for vendors, to make sure we real users on the platform",
      "Allow vendors to create a customize business profile for their business",
      "Vendors where able to share their customize business page on social platforms",
      "Vendors where able to create a customize gig for their services",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },

  {
    id: "03",
    title: "FIATPLUG",
    description:
      "Fiatplug is a digital currency peer to peer system, a platform that ensures a seamless and secure trading experience for selling gift cards and cryptocurrencies. I joined a team of product engineers working across web and mobile using Flutter.",
    coverImg: "/fatPlug.jpg",
    gradient: "from-[#D8B4FE] to-[#818CF8]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://www.fiatplug.com/",
    role: "Frontend Developer",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "Shadcn",
      "TailwindCSS",
      "PWA",
    ],
    features: [
      "Convert the merchant dashboard to PWA",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between users and vendors using Pusher",
      "Implement PWA features such as service workers, offline support, and push notifications.",
      "Setup the frontend architecture, using NextJS, ReduxThunk. every endpoint are managed independently",
      "Handle complex data flow and synchronization between components",
      "KYC integration for user, to make sure we real users on the platform",
      "Integrate with various third-party APIs and services",
      "Participate in code reviews and provide constructive feedback.",
      "Perform code refactoring to improve code maintainability and readability",
      "Work effectively in a team, communicating ideas and solutions clearly.",
      "In charge in building the Merchant App and Customer App (PWA).",
    ],
  },
  {
    id: "04",
    title: "Fleckr",
    description:
      "Cohexa AI note dictation system is pivotal in meticulously documenting patient discussions, and ensuring the integrity of medical records.",
    coverImg: "/Fleckr.jpg",
    gradient: "from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://fleckr.vercel.app/",
    role: "Frontend Developer (Freelancer)",
    stacks: ["Typescript", "React", "Next", "Redux", "TailwindCSS", "PWA"],
    features: [
      "Waitlist system, that endedup validation 698 users",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between vendors and customers",
      "Users can find vendors base on their current location",
      "Wallet system, vendors can recieve money from customer",
      "Auto matching system between vendors and users",
      "KYC integration for vendors, to make sure we real users on the platform",
      "Allow vendors to create a customize business profile for their business",
      "Vendors where able to share their customize business page on social platforms",
      "Vendors where able to create a customize gig for their services",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },
];

export const projects = [
  {
    id: "02",
    title: "Aquatrack",
    description:
      "AquaTrack is the innovative platform connecting fish farmers to a worldwide market, providing data-driven insights, and promoting sustainable practices.",
    coverImg: "/aquatrack-landing.jpg",
    gradient: "from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://www.aquatrackinc.com/management-system",
    role: "Lead Frontend Developer",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "TailwindCSS",
      "Shadcn",
      "PWA",
    ],
    features: [
      "Setup the frontend architecture, using NextJS, ReduxThunk. every endpoint are managed independently to improve performance and scalebility for the data fetching",
      "Lead 3 Frontend developer and 2 Interns during this product building",
      "Implemented a Secure Login with HTTPOnly Cookie",
      "Implemented Charts using Rechart",
      "Implemented Adding task and a real time reminder",
      "Delivered 2weeks ealiar before the deadline",
      "Enlighthen the client on features they need to add that's not in their PRD",
      "Implemented a subscription model, users can subscribe to premiunm plan using PayStack for making payment.",
      "Worked on Complex forms and making every bit responsive on all screens",
      "Worked closely with the backend team and design team to always be in sync with the product goal",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },
  {
    id: "01",
    title: "EASEPLAN",
    description:
      "An event planning platform that connects event owners to event planners and vendors could be viable in countries in Africa.",
    coverImg: "/EasePlan.jpg",
    gradient: "from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]",
    githubLink: "",
    siteLink: "https://www.easeplan.io",
    role: "Co-founder / Frontend Lead",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "MUI",
      "TailwindCSS",
      "PWA",
    ],
    features: [
      "Waitlist system, that endedup validation 698 users",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between vendors and customers",
      "Users can find vendors base on their current location",
      "Wallet system, vendors can recieve money from customer",
      "Auto matching system between vendors and users",
      "KYC integration for vendors, to make sure we real users on the platform",
      "Allow vendors to create a customize business profile for their business",
      "Vendors where able to share their customize business page on social platforms",
      "Vendors where able to create a customize gig for their services",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },

  {
    id: "03",
    title: "FIATPLUG",
    description:
      "Fiatplug is a digital currency peer to peer system, a platform that ensures a seamless and secure trading experience for selling gift cards and cryptocurrencies. I joined a team of product engineers working across web and mobile using Flutter.",
    coverImg: "/fatPlug.jpg",
    gradient: "from-[#D8B4FE] to-[#818CF8]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://www.fiatplug.com/",
    role: "Frontend Developer",
    stacks: [
      "Typescript",
      "React",
      "Next",
      "Redux",
      "Shadcn",
      "TailwindCSS",
      "PWA",
    ],
    features: [
      "Convert the merchant dashboard to PWA",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between users and vendors using Pusher",
      "Implement PWA features such as service workers, offline support, and push notifications.",
      "Setup the frontend architecture, using NextJS, ReduxThunk. every endpoint are managed independently",
      "Handle complex data flow and synchronization between components",
      "KYC integration for user, to make sure we real users on the platform",
      "Integrate with various third-party APIs and services",
      "Participate in code reviews and provide constructive feedback.",
      "Perform code refactoring to improve code maintainability and readability",
      "Work effectively in a team, communicating ideas and solutions clearly.",
      "In charge in building the Merchant App and Customer App (PWA).",
    ],
  },
  {
    id: "04",
    title: "Fleckr",
    description:
      "Cohexa AI note dictation system is pivotal in meticulously documenting patient discussions, and ensuring the integrity of medical records.",
    coverImg: "/Fleckr.jpg",
    gradient: "from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]",
    githubLink: "https://github.com/calebbenjin",
    siteLink: "https://fleckr.vercel.app/",
    role: "Frontend Developer (Freelancer)",
    stacks: ["Typescript", "React", "Next", "Redux", "TailwindCSS", "PWA"],
    features: [
      "Waitlist system, that endedup validation 698 users",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between vendors and customers",
      "Users can find vendors base on their current location",
      "Wallet system, vendors can recieve money from customer",
      "Auto matching system between vendors and users",
      "KYC integration for vendors, to make sure we real users on the platform",
      "Allow vendors to create a customize business profile for their business",
      "Vendors where able to share their customize business page on social platforms",
      "Vendors where able to create a customize gig for their services",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },
  {
    id: "05",
    title: "CAPITALROLLUP",
    description:
      "With just one click, discover and invest into some of the best performing crypto indexes.",
    coverImg: "/aquatrack-landing.jpg",
    gradient: "from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]",
    githubLink: "",
    siteLink: "https://capitalrollup.com",
    role: "Co-founder / Frontend Lead",
    stacks: ["Typescript", "React", "Next", "Redux", "TailwindCSS", "PWA"],
    features: [
      "Design and build reusable code and libraries for future use, increasing development efficiency by 30%",
      "Secure Login with HTTPOnly Cookie",
      "Real time chat app between vendors and customers",
      "Users can find vendors base on their current location",
      "Wallet system, vendors can recieve money from customer",
      "Auto matching system between vendors and users",
      "KYC integration for vendors, to make sure we real users on the platform",
      "Allow vendors to create a customize business profile for their business",
      "Vendors where able to share their customize business page on social platforms",
      "Vendors where able to create a customize gig for their services",
      "PWA enabled with Notification",
      "Optimize and increase performance",
      "Build the admin dashboard, that allow management to manage every activiate on the platform.",
    ],
  },
  {
    id: "06",
    title: "SUREODDS",
    description: "A sports betting bookmaker social platform.",
    coverImg: "/sureodds.png",
    gradient: "from-[#D8B4FE] to-[#818CF8]",
    githubLink: "",
    siteLink: "https://capitalrollup.com",
    role: "Founder/Creator",
    stacks: ["Typescript", "React", "Next", "Redux", "TailwindCSS", "PWA"],
    features: [
      "This is just a personal pet project building in my spare time",
    ],
  },
];
